BillingApp.Web/JeyamBillingApp/Areas/Bills/Controllers/DailyWorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JeyamBillingApp.Business.Interfaces;
using JeyamBillingApp.Web.Model;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JeyamBillingApp.Web.Areas.Bills.Controllers
{
    [Area("Bills")]
    [Authorize]
    public class DailyWorkController : Controller
    {
        private readonly IDailyWorkService _dailyWorkService;

        public DailyWorkController(IDailyWorkService dailyWorkService)
        {
            _dailyWorkService = dailyWorkService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var result = _dailyWorkService.GetDailyWorks();
            if (result.Any())
            {
                foreach (var work in result)
                {
                    work.TotalHoursText = getTimeDiffrence(work.StartTime, work.EndTime);
                }
            }
            return Json(result.ToDataSourceResult(request));
        }

        [HttpPost]
        public ActionResult Add([DataSourceRequest] DataSourceRequest request, DailyWorkViewModel dailyWorkViewModel)
        {
            if (dailyWorkViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    dailyWorkViewModel = _dailyWorkService.Add(dailyWorkViewModel);

                    dailyWorkViewModel.TotalHoursText = getTimeDiffrence(dailyWorkViewModel.StartTime, dailyWorkViewModel.EndTime);
                }
            }
            return Json(new[] { dailyWorkViewModel }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, DailyWorkViewModel dailyWorkViewModel)
        {
            if (dailyWorkViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    dailyWorkViewModel = _dailyWorkService.Update(dailyWorkViewModel);

                    dailyWorkViewModel.TotalHoursText = getTimeDiffrence(dailyWorkViewModel.StartTime, dailyWorkViewModel.EndTime);
                }
            }
            return Json(new[] { dailyWorkViewModel }.ToDataSourceResult(request, ModelState));
        }


        [HttpPost]
        public ActionResult Delete([DataSourceRequest] DataSourceRequest request, DailyWorkViewModel dailyWorkViewModel)
        {
            if (dailyWorkViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    _dailyWorkService.Delete(dailyWorkViewModel);
                }
            }
            return Json(new[] { dailyWorkViewModel }.ToDataSourceResult(request, ModelState));
        }

        public JsonResult GetSitesNameList()
        {
            return Json(_dailyWorkService.GetSitesName());
        }

        public string getTimeDiffrence(DateTime startDate, DateTime endDate)
        {
            var _eventDurationHours = Convert.ToInt32(((endDate.Subtract(startDate).Days * 24) + (endDate.Subtract(startDate)).Hours));

            var _eventDurationMinutes = endDate.Subtract(startDate).Minutes;

            var _eventDurationText = $"{_eventDurationHours}h {_eventDurationMinutes}m";

            return _eventDurationText;
        }

        public JsonResult GetTimeDiffrenceText(DateTime startDate, DateTime endDate)
        {
            var _eventDurationText = getTimeDiffrence(startDate, endDate);

            var _span = getTimeDiffrenceDecimal(startDate, endDate);

            return Json(new { eventDurationText = _eventDurationText, eventDuration = _span });
        }

        public double getTimeDiffrenceDecimal(DateTime startDate, DateTime endDate)
        {
            return (endDate - startDate).TotalHours;
        }
    }
}

BillingApp.Web/JeyamBillingApp/Areas/Bills/Controllers/GenerateBillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JeyamBillingApp.Web.Areas.Bills.Controllers
{
    [Area("Bills")]
    [Authorize]
    public class GenerateBillController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BillingApp.Web/JeyamBillingApp/Areas/Customers/Controllers/SitesInfoController.cs
using System.Linq;
using System.Threading.Tasks;
using JeyamBillingApp.Business.Interfaces;
using JeyamBillingApp.Web.Model;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JeyamBillingApp.Web.Areas.Customers.Controllers
{
    [Area("Customers")]
    [Authorize]
    public class SitesInfoController : Controller
    {

        private readonly ISiteService _siteService;

        public SitesInfoController(ISiteService siteService)
        {
            _siteService = siteService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var result = _siteService.GetSites();
            return Json(result.ToDataSourceResult(request));
        }

        [HttpPost]
        public ActionResult Add([DataSourceRequest] DataSourceRequest request, SiteViewModel siteViewModel)
        {
            if (siteViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    siteViewModel = _siteService.Add(siteViewModel);
                }
            }
            return Json(new[] { siteViewModel }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, SiteViewModel siteViewModel)
        {
            if (siteViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    siteViewModel = _siteService.Update(siteViewModel);
                }
            }
            return Json(new[] { siteViewModel }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Delete([DataSourceRequest] DataSourceRequest request, SiteViewModel siteViewModel)
        {
            if (siteViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    _siteService.Delete(siteViewModel);
                }
            }
            return Json(new[] { siteViewModel }.ToDataSourceResult(request, ModelState));
        }
    }
}

BillingApp.Web/JeyamBillingApp/Areas/Vechicles/Controllers/VechiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JeyamBillingApp.Business.Interfaces;
using JeyamBillingApp.Web.Model;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JeyamBillingApp.Web.Areas.Vechicles.Controllers
{
    [Area("Vechicles")]
    [Authorize]
    public class VechiclesInfoController : Controller
    {
        private readonly IVechicleService _vechicleService;

        public VechiclesInfoController(IVechicleService vechicleService)
        {
            _vechicleService = vechicleService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var result = _vechicleService.GetVechicles();
            return Json(result.ToDataSourceResult(request));
        }

        [HttpPost]
        public ActionResult Add([DataSourceRequest] DataSourceRequest request, VechicleViewModel vechicleViewModel)
        {
            if (vechicleViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    vechicleViewModel = _vechicleService.Add(vechicleViewModel);
                }
            }
            return Json(new[] { vechicleViewModel }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, VechicleViewModel vechicleViewModel)
        {
            if (vechicleViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    vechicleViewModel = _vechicleService.Update(vechicleViewModel);
                }
            }
            return Json(new[] { vechicleViewModel }.ToDataSourceResult(request, ModelState));
        }

        [HttpPost]
        public ActionResult Delete([DataSourceRequest] DataSourceRequest request, VechicleViewModel vechicleViewModel)
        {
            if (vechicleViewModel != null && ModelState.IsValid)
            {
                if (ModelState.IsValid)
                {
                    _vechicleService.Delete(vechicleViewModel.VechicleId);
                }
            }
            return Json(new[] { vechicleViewModel }.ToDataSourceResult(request, ModelState));
        }
    }
}

BillingApp.Web/JeyamBillingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Constants.CompanyName  </title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/lib/kendo-ui/style/kendo.bootstrap-v4.min.css" rel="stylesheet" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
        <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2019.1.220/styles/kendo.bootstrap-v4.min.css" />
    </environment>

    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/page-loader.css" rel="stylesheet" />

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/kendo-ui/js/kendo.all.min.js"></script>
        <script src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"></script>
        <script src="~/lib/kendo-ui/js/jszip.min.js"></script>
        <script src="~/lib/kendo-ui/js/cultures/kendo.culture.en-IN.min.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>

        <script src="https://kendo.cdn.telerik.com/2019.1.220/js/kendo.all.min.js"
                asp-fallback-src="~/lib/kendo-ui/js/kendo.all.min.js"
                asp-fallback-test="window.kendo">
        </script>
        <script src="https://kendo.cdn.telerik.com/2019.1.220/js/kendo.aspnetmvc.min.js"
                asp-fallback-src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"
                asp-fallback-test="kendo.data.transports['aspnetmvc-ajax']">
        </script>

        <script src="https://kendo.cdn.telerik.com/2019.1.220/js/jszip.min.js"
                asp-fallback-src="~/lib/kendo-ui/js/kendo.aspnetmvc.min.js"
                asp-fallback-test="kendo.data.transports['aspnetmvc-ajax']">
        </script>

        <script src="https://kendo.cdn.telerik.com/2019.1.220/js/cultures/kendo.culture.en-IN.min.js"
                asp-fallback-src="~/lib/kendo-ui/js/cultures/kendo.culture.en-IN.min.js"></script>

    </environment>

    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <div class="loading">Loading...</div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/site-logo.jpg" alt="">
                    @Constants.CompanyName
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @{

                            if (SignInManager.IsSignedIn(User))
                            {

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Vechicles
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="Vechicles" asp-controller="VechiclesInfo" asp-action="Index">Vechicles Info</a>
                                        <a class="dropdown-item" asp-area="Vechicles" asp-controller="Maintenance" asp-action="Index">Maintenance</a>
                                    </div>
                                </li>

                                @*<li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Customers" asp-controller="CustomersInfo" asp-action="Index">Customers</a>
                                    <a class="nav-link text-dark" asp-area="Customers" asp-controller="SitesInfo" asp-action="Index">Sites</a>
                                </li>*@

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Customers
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="Customers" asp-controller="CustomersInfo" asp-action="Index">Customers</a>
                                        <a class="dropdown-item" asp-area="Customers" asp-controller="SitesInfo" asp-action="Index">Sites</a>
                           
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Bills
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" asp-area="Bills" asp-controller="DailyWork" asp-action="Index">Daily Work</a>
                                        <a class="dropdown-item" asp-area="Bills" asp-controller="GenerateBill" asp-action="Index">Generate Bill</a>
                                        <a class="dropdown-item" asp-area="Bills" asp-controller="GenerateBillReport" asp-action="Index">Generate Bill Report</a>
                                    </div>
                                </li>
                            }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="div_content" class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6">
                    &copy; @DateTime.Now.Year.ToString() - @Constants.CompanyName
                </div> 
                <div class="col-md-6 float-right text-right">
                    <img src="https://letsencrypt.org/images/le-logo-wide.png" alt="" height="35" />
                </div>
            </div>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>